  body {
    background: #ffffff;
    color: black;
    }
  body, a, h4, h3, h2, h1, p, div, span {
    font-family: helvetica, sans-serif;
    }
  h1, h2, h3, h4, h5, h6, h7 {
    background: #a04040;
    border: solid 1px black;
    border-bottom: none;
    width: 45%; 
    padding: 0.2em;
    padding-left: 0.5em;
    color: white;
    margin: 0em;
    -moz-border-radius: 1em 1em 0px 0px;
    }
  div.clear {
    clear: both;
    }
  div.menu {
    background: #a04040;
    border: solid 1px black; 
    padding: 0.5em;
    margin: 0em;
    float: right;
    text-align: right;
    color: white;
    -moz-border-radius: 1em 1em 0px 0px;
    }
  div.text {
    background: #d0d0d0;
    border: solid 1px black; 
    padding: 0.5em;
    margin: 0em;
    margin-bottom: 0.5em;
    color: black;
    -moz-border-radius: 0px 1em 0px 0px;
    }
  table {
    border-collapse: collapse;
    margin: 0em;
    border: solid 1px black; 
    margin-bottom: 0.5em;
    margin-left: 0.5em;
    padding: 0px;
    cell-spacing: 0;
    cell-padding: 0;
    }
  div.percent {
    width: 100px;
    border: 1px solid black;
    height: 0.5em;
    padding: 0;
    margin: 0;
    }
  span.percent {
    background: #ff0000;
    min-width: 1px;
    max-width: 100px;
    border: none;
    height: 0.5em;
    padding: 0;
    margin: 0;
    float: left;
    }
  input.submit {
    margin-left: 1em;
    }
  input.browse {
    margin-left: 1em;
    }
  input.reset {
    margin-left: 2em;
    }
  table.menu {
    float: right;
    margin: 0;
    padding: 0;
    }
  table.auth {
    margin-bottom: 0.5em;
    }
  table.edit {
    margin: 0.5em;
    }
  td.editfieldname {
    padding: 2px;
    padding-left: 0.5em;
    padding-right: 0.5em;
    border-right: 1px solid grey;
    }
  td.editfield {
    padding: 4px;
    padding-left: 0.5em;
    padding-right: 0.5em;
    }
  td.auth {
    padding: 5px;
    }
  th.auth {
    padding: 5px;
    background: #ff2020;
    }
  tr {
    margin: 0;
    padding: 0px;
    }   
  td {
    font-size: 0.8em;
    margin: 0px;
    padding: 2px;
    padding-left: 4px;
    padding-right: 4px;
    border: 1px solid black;
    background: #f0f0f0;
    }
  td.id {
    text-align: right;
    }
  td.noreturn  { background: #ff8020; }
  td.unknown   { background: #e0e0e0; }
  td.offline   { background: #ff0000; }
  td.online    { background: #00ff00; }
  td.nocon     { background: #fff000; }
  td.tobedone  { background: #80ff80; }
  td.solved    { background: #ff80ff; }
  td.suspended { background: #ffff80; }
  td.failed    { background: #ff8080; }
  td.bad       { background: #ff0000; }
  td.verify    { background: #40ff40; }
  td.issued    { background: #ffff80; }
  td.done      { background: #e0ffe0; }
  td.waiting   { background: #40d040; }
  th {
    font-size: 0.8em;
    background: #a04040;
    margin: 0px;
    padding: 3px;
    border: 1px solid black;
    color: white;
    }
  ul {
    list-style-type: square;
    }
  td.DIR_FILE
    {
    background: #ffffff;
    border: none;
    border-bottom: 1px solid;
    border-left: 1px solid;
    border-right: 1px solid;
    }
  td.DIR_DIR, td.DIR_UPDIR
    {
    background: #10d0e0;
    border: none;
    border-bottom: 1px solid;
    border-left: 1px solid;
    border-right: 1px solid;
    }
  td.DIR
    {
    padding-left: 0.3em;
    text-align: left;
    border: none;
    border-bottom: 1px solid;
    }
  td.DIR_ODD
    {
    background: #ffffd0;
    padding-left: 0.3em;
    text-align: left;
    border: none;
    border-bottom: 1px solid;
    }
  td.DIR_RIGHT
    {
    text-align: right;
    padding-left: 1em;
    padding-right: 0.3em;
    border: none;
    border-bottom: 1px solid;
    border-right: 1px solid;
    }
  td.DIR_RIGHT_ODD
    {
    background: #ffffd0;
    text-align: right;
    padding-left: 1em;
    padding-right: 0.3em;
    border: none;
    border-bottom: 1px solid;
    border-right: 1px solid;
    }
  li.help {
    margin-bottom: 0.3em;
    }
  p {
    color: black;
    margin: 0em;
    padding: 0.5em;
    }
  p.small {
    font-family: courier-new, courier, monospaced;
    font-size: 0.5em;
    }
  pre, pre.error {
    margin: 0.3em;
    margin-bottom: 0em;
    padding: 2px;
    margin-left: 1.0em;
    }
  pre.error {
    border: solid 1px black;
    }
  a:link { 
    color: #505050;
    padding: 2px;
    margin: 0;
    }
  a:visited { 
    color: #202020;
    padding: 2px;
    margin: 0;
    }
  a:link.m { 
    color: #fff0f0;
    padding: 2px;
    margin: 0;
    }
  a:visited.m { 
    color: #fff0f0;
    padding: 2px;
    margin: 0;
    }
  a:hover.m, a:hover { 
    background-color: #ffff20;
    border: black 1px solid;
    padding: 1px;
    margin: 0;
    color: black;
    }
