<li><a href="##selfhelp_new##">What's new </a>
<li><a href="##selfhelp_config##">DiCoP Config file format and documentation </a>
<li><a href="##selfhelp_files##">File structure of the server/client</a>
<li><a href="##selfhelp_glossary##">Glossary with often used acronyms or words</a>
<li><a href="##selfhelp_trouble##">Troubleshooting </a>
<li><a href="##selfhelp_proxy##">The internal details of a server acting as a proxy</a>
<li><a href="##selfhelp_dicopp##">Details for the dicopp daemon</a>
